name: Branch Cleanup

on: delete

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v3
        with:
          package-version-ids: ${{ github.event.ref }}
          package-name: arma-reforger
